#!/usr/bin/expect --

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set host [lindex $argv 0]

set timeout 10
spawn rdesktop -u {} $host
match_max 100000
expect "Do you trust this certificate (yes/no)? "
send -- "yes\r"
expect eof
