name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
            uses: actions/setup-python@v1
            with:
            python-version: 3.8
        - name: Build the local UI with docker-compose
            run: |
            sudo apt -y install python3-setuptools
            make docker
        - name: Build the dev envrionment with docker-compose
            run: |
            sudo apt -y install python3-setuptools
            make dev
